# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/icecollection/multisite/models/setting/fields.yaml

# Model Class name
modelClass: IceCollection\Multisite\Models\Setting

# Default redirect location
defaultRedirect: IceCollection/multisite/settings

# Create page
create:
    title: icecollection.multisite::lang.controller.create
    redirect: icecollection/multisite/settings/update/:id
    redirectClose: icecollection/multisite/settings

# Update page
update:
    title: icecollection.multisite::lang.controller.create
    redirect: icecollection/multisite/settings
    redirectClose: icecollection/multisite/settings
